project_id: '543760'

append_commit_message: false
base_path: .
preserve_hierarchy: true

pull_request_title: 'feat(i18n): new translation updates'
commit_message: 'chore(i18n): new translations for %original_file_name% (%language%)'

files:
  - source: /services/bot/locales/en-US/translation.json
    translation: /services/bot/locales/%locale%/%original_file_name%
