version: '3.7'

services:
    bot:
        build:
            context: .
            dockerfile: ./apps/bot/Dockerfile
        ports:
            - '2399:2399'
        restart: unless-stopped
        env_file:
            - ./.env.dev

    postgres:
        build:
            context: ./docker/postgres
        environment:
            POSTGRES_USER: 'admin'
            POSTGRES_PASSWORD: 'doctordoctor'
            POSTGRES_DB: 'thoth'
        volumes:
            - postgres-storage:/var/lib/postgresql/data
            - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

        ports:
            - '5432:5432'
        restart: unless-stopped

    redis:
        image: redis:alpine
        restart: unless-stopped
        ports:
            - '6379:6379'

volumes:
    postgres-storage:
