version: '3.7'

services:
    bot:
        build:
            context: .
            dockerfile: ./apps/bot/Dockerfile
        ports:
            - '2399:2399'
        restart: unless-stopped
        env_file:
            - ./.env.dev

    postgres:
        build:
            context: ./docker/postgres
        environment:
            POSTGRES_USER: 'admin'
            POSTGRES_PASSWORD: 'doctordoctor'
            POSTGRES_DB: 'thoth'
        volumes:
            - postgres-storage:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        restart: unless-stopped

    redis:
        image: redis:alpine
        restart: unless-stopped
        ports:
            - '6379:6379'

    prometheus:
        build:
            context: ./docker/prometheus
        restart: unless-stopped
        command: --config.file=/etc/prometheus/prometheus.yml --log.level=debug
        ports:
            - 9090:9090
        volumes:
            - prometheus-storage:/prometheus

    grafana:
        build:
            context: ./docker/grafana
        restart: unless-stopped
        environment:
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: admin
            GF_USERS_ALLOW_SIGN_UP: 'false'
            GF_AUTH_ANONYMOUS_ENABLED: true
        ports:
            - 3000:3000
        volumes:
            - grafana-storage:/var/lib/grafana

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:latest
        ports:
            - 8080:8080
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro

volumes:
    prometheus-storage:
    grafana-storage:
    postgres-storage:
