version: '3.7'

services:
    thoth:
        image: ghcr.io/fyko/thoth:main
        expose:
            - '21983'
        restart: unless-stopped
        env_file:
            - ./.env.prod
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:21983/health']
            interval: 10s
            timeout: 5s
            retries: 5
        labels:
            - 'com.centurylinklabs.watchtower.enable=true'

    postgres:
        build:
            context: ./docker/postgres
        environment:
            POSTGRES_USER: 'admin'
            POSTGRES_PASSWORD: 'doctordoctor'
            POSTGRES_DB: 'thoth'
        expose:
            - '5432'
        healthcheck:
            test: ['CMD', 'pg_isready', '-U', 'admin', '-d', 'thoth']
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - postgres-storage:/var/lib/postgresql/data
        restart: unless-stopped

    redis:
        image: redis:alpine
        restart: unless-stopped
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 10s
            timeout: 5s
            retries: 5
        expose:
            - '6379'

    watchtower:
        image: containrrr/watchtower
        environment:
            - TZ=America/Denver
            - WATCHTOWER_LABEL_ENABLE=true
            - WATCHTOWER_CLEANUP=true
            - WATCHTOWER_POLL_INTERVAL=60 # 1 minute
            - WATCHTOWER_NOTIFICATIONS=slack
            - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

volumes:
    postgres-storage:
