version: '3.7'

services:
  bot:
    image: ghcr.io/fyko/thoth:latest
    restart: unless-stopped
    env_file:
      - ./.env

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
