version: '3.7'

services:
  thoth:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '2399:2399'
    restart: unless-stopped
    env_file:
      - ./.env.dev

  gateway:
    image: twilightrs/gateway-queue
    environment:
      HOST: '0.0.0.0'
      PORT: '2398'
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    env_file:
      - ./.env.dev
    ports:
      - '2398:2398'

  thothd:
    build:
      context: ./thothd
      dockerfile: Dockerfile
    environment:
      GATEWAY_HOST: 'gateway'
      GATEWAY_PORT: '2398'
    ports:
      - '2397:2397'
    restart: unless-stopped
    env_file:
      - ./.env.dev
      
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - '6379:6379'

  prometheus:
    build:
      context: ./docker/prometheus
    restart: unless-stopped
    command: --config.file=/etc/prometheus/prometheus.yml --log.level=debug
    ports:
      - 9090:9090
    volumes:
      - prometheus-storage:/prometheus

  grafana:
    build:
      context: ./docker/grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: 'false'
      GF_AUTH_ANONYMOUS_ENABLED: true
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  prometheus-storage:
  grafana-storage:
