version: '3.7'

services:
  bot:
    image: ghcr.io/fyko/thoth:latest
    restart: unless-stopped
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    ports:
      - '2399:2399'
    env_file:
      - ./.env

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=600 # 10 minutes
      - TZ=America/Denver
      - WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
