version: '3.7'

services:
  thoth:
    image: ghcr.io/fyko/thoth:latest
    ports:
      - '2399:2399'
    restart: unless-stopped
    env_file:
      - ./.env
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

  gateway:
    image: twilightrs/gateway-queue
    environment:
      HOST: '0.0.0.0'
      PORT: '2398'
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    env_file:
      - ./.env
    ports:
      - '2398:2398'

  thothd:
    image: ghcr.io/fyko/thothd:latest
    environment:
      GATEWAY_HOST: 'gateway'
      GATEWAY_PORT: '2398'
    ports:
      - '2397:2397'
    restart: unless-stopped
    env_file:
      - ./.env
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

  prometheus:
    build:
      context: ./docker/prometheus
    restart: unless-stopped
    command: --config.file=/etc/prometheus/prometheus.yml --log.level=debug
    ports:
      - 9090:9090
    volumes:
      - prometheus-storage:/prometheus

  grafana:
    build:
      context: ./docker/grafana
    restart: unless-stopped
    environment:
      GF_SERVER_DOMAIN: ${GF_SERVER_DOMAIN}
      GF_SERVER_ROOT_URL: ${GF_SERVER_ROOT_URL}
      GF_SERVE_FROM_SUB_PATH: 'true'
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: 'false'
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
    env_file:
      - ./.env
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=600 # 10 minutes
      - TZ=America/Denver
      - WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  prometheus-storage:
  grafana-storage:
