version: '3.7'

services:
  gateway:
    image: spectacles/gateway
    restart: unless-stopped
    env_file: ./docker/gateway/.env
    
  proxy:
    image: spectacles/proxy
    restart: unless-stopped
    env_file: ./docker/proxy/.env

  rabbit:
    image: rabbitmq:alpine
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=fyko
      - RABBITMQ_DEFAULT_PASS=doctordoctor
    ports:
      - 5672:5672
    expose:
      - 5672

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
    expose: 
      - 6379
    volumes:
      - "redis_data:/data"

volumes:
  redis_data: