{
 "title": "Thoth",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Commands",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    { "expr": "sum(thoth_commands)", "legendFormat": "{{route}}, {{status_code}}" }
   ]
  },
  {
   "title": "Guilds",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "thoth_metrics_guilds", "legendFormat": "{{route}}, {{status_code}}" }
   ]
  },
  {
   "title": "WOTD Subscribers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "thoth_wotd_subscribers", "legendFormat": "{{route}}, {{status_code}}" }
   ]
  },
  {
   "title": "Process Memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_nodejs_external_memory_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{name=\"thoth-thoth-1\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "thoth_commands{success=\"true\"}",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "thoth_nodejs_heap_space_size_total_bytes",
     "legendFormat": "{{space}}"
    }
   ]
  },
  {
   "title": "Container Memory",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_cache{name=~\".+\", container_label_com_docker_compose_project=\"thoth\"}) by (container_label_com_docker_compose_service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Guilds",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "thoth_metrics_guilds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Thoth Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "{container=\"thoth-thoth-1\"} |= ``"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "thoth_nodejs_external_memory_bytes",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_commands{success=\"true\"}",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "thoth_commands{success=\"true\"}",
     "legendFormat": "{{command}}"
    }
   ]
  }
 ]
}