global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'thoth'
    static_configs:
      - targets: ['thoth:21983']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
