name: Continuous Deployment (thoth)

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'src/**/*.ts'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'Dockerfile'
      - 'locales/**'

env:
  slug: ghcr.io/Fyko/thoth
  dockerfile: ./Dockerfile

jobs:
  docker:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ env.slug }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ env.slug }}-buildx-

      - name: Login to Google Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.slug }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        shell: bash
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
