name: Continuous Deployment (commands)

# todo: move this to a kube pre-deploy step
on:
    # push:
    #   branches: [main]
    #   paths:
    #     - 'commands.lock.json'
    #     - '.github/workflows/cd_commands.yml'
    workflow_dispatch:

jobs:
    deploy:
        name: Deploy Updated Global Commands
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: PUT Global Commands
              run: |
                  curl -X PUT https://discord.com/api/v10/applications/${{ secrets.DISCORD_APPLICATION_ID }}/commands \
                    -H "Authorization: Bot ${{ secrets.DISCORD_TOKEN }}" \
                    -H "Content-Type: application/json" \
                    -d @./commands.lock.json | jq
