name: Continuous Deployment (commands)

on:
  push:
    branches: [main]
    paths:
      - 'commands.lock.json'
      - '.github/workflows/cd_commands.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Updated Global Commands
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: PUT Global Commands
        run: |
          curl -X PUT https://discord.com/api/applications/${{ secrets.DISCORD_APPLICATION_ID }}/commands \
            -H "Authorization: Bot ${{ secrets.DISCORD_TOKEN }}" \
            -H "content-type: application/json" \
            -d @./commands.lock.json
