name: Continuous Deployment (thothd)

on:
  push:
    branches: [main]
    paths: ['thothd/**']

jobs:
  docker:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: fyko/thothd
          tags: latest ${{ github.sha }} # important!
          context: ./thothd
          dockerfiles: |
            ./thothd/Dockerfile
          build-args: |
            CREATED_AT=${{ env.datetime }}
            GITHUB_SHA=${{ github.sha }}

      - name: Publish
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
