name: Testing

on:
  push:
    branches-ignore: [feat/translations]
  pull_request:
    branches-ignore: [feat/translations]

jobs:
  tests:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        uses: trufflehq/truffle-packages/actions/yarn@99bfffab89199c599f12ace60f9bdd0025824865

      - name: Lint
        run: yarn run lint

      - name: Build
        run: yarn run build
