name: Testing

on:
  push:
    branches-ignore: [feat/translations]
  pull_request:
    branches-ignore: [feat/translations]

jobs:
  tests:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        uses: discordjs/discord.js/packages/actions/src/pnpmCache@e96a8a977fdbd44fb8795fdbbcfb42fb667c4554

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build
