name: Testing

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: [self-hosted]
    name: Lint
    steps:
      - uses: actions/checkout@v3

      - name: Setup Volta
        uses: volta-cli/action@v3

      - name: Install Dependencies
        run: yarn --immutable

      - name: Run ESLint
        run: yarn lint

  build:
    runs-on: [self-hosted]
    name: Build
    steps:
      - uses: actions/checkout@v3

      - name: Setup Volta
        uses: volta-cli/action@v3

      - name: Install Dependencies
        run: yarn --immutable

      - name: Compile code
        run: yarn build
