name: Testing

on:
  push:
    branches-ignore: [feat/translations]
  pull_request:
    branches-ignore: [feat/translations]

jobs:
  tests:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.11

      - uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/turbo.json') }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - run: bun install

      - run: bunx turbo run lint --concurrency=4 --cache-dir=.turbo

      - run: bunx turbo run build --concurrency=4 --cache-dir=.turbo
